### ISSUE TITLE
>>xkcd parameter to specify comic episode #

### ISSUE THREAD

**Issue by EverTokki** [abraker95/apex-sigma#13]
Requesting to add an optional parameter to >>xkcd <number>. The parameter would take the number, which specifies the number(episode) of the comic to display. If parameter is not given, output random comic out of all xkcd episodes.

**Comment by abraker95** [comment]
Created a [duplicate issue](https://github.com/abraker95/apex-sigma/issues/15) not knowing about this one. Keeping other one for simplicity.

Closed
