### ISSUE TITLE
Tic-Tac-Toe saying you lost when you won

### ISSUE THREAD

**Issue by abraker95** [abraker95/apex-sigma#16]
Seems to happen if there is one square remaining or the AI would have won next turn

Example cases:
![alt tag](http://i.imgur.com/jWC0JeZ.png)
![alt tag](http://i.imgur.com/2lBe7AI.png)
![alt tag](http://i.imgur.com/kpJHRRO.png)

**Comment by johnmedina999** [comment]
This command needs a few other fixes as well.

- Create tie results screen. It should display "tie" and end the current game.
- Invoking the command by itself should bring up the help text.
- AI could use a tune-up. It could try to detect when the player is attempting to make a line. This might not be necessary, though, and may result in the game being too hard. Ultimately optional.

**Comment by johnmedina999** [comment]
Are we done with this issue?
