### ISSUE TITLE
install.py not working on Windows x86_64

### ISSUE THREAD

**Issue by johnmedina999** [abraker95/apex-sigma#38]
Trying to install the dependencies for this project leads to the following error:

![image](https://user-images.githubusercontent.com/12093732/47967609-fd17dc80-e013-11e8-9f1a-b20572946ec6.png)

**Comment by abraker95** [comment]
fixed via https://github.com/abraker95/apex-sigma/commit/a0f13e3e69881fa771c71bbd7330dce67f49c732
