### ISSUE TITLE
cat command not working

### ISSUE THREAD

**Issue by johnmedina999** [abraker95/apex-sigma#47]
![image](https://user-images.githubusercontent.com/12093732/60862453-75055a80-a1d2-11e9-9bb8-cfd0e2a5d662.png)
![image](https://user-images.githubusercontent.com/12093732/60862504-923a2900-a1d2-11e9-9170-af773e71c6e2.png)

**Comment by johnmedina999** [comment]
I think this doesn't work because the URL for getting cat images requires an API key which isn't enabled, while the dog command is not API-dependant. Perhaps a rewrite is in order; or perhaps it's best to leave it as is.

**Comment by johnmedina999** [comment]
This command is addressed in Issue #49 and Pull Request #52. Are we done with this issue?

**Comment by abraker95** [comment]
Based on the docs at https://docs.thecatapi.com/, the command might be defunc

**Comment by johnmedina999** [comment]
You're right, this doesn't need an API key after all. I can even do it in my browser. This should be an easy fix.
