### ISSUE TITLE
Crash due to emoji

### ISSUE THREAD

**Issue by abraker95** [abraker95/apex-sigma#54]
![](https://i.imgur.com/1LZnCOE.png)

**Comment by abraker95** [comment]
Discord changed how emojis work: https://www.reddit.com/r/Discord_Bots/comments/dyd1pz/reacting_with_emotes_causes_bot_to_crash/

Need to upgrade discord.py to 1.2.5

**Comment by johnmedina999** [comment]
This seems to be fixed. Have you updated yet?

**Comment by abraker95** [comment]
yes

**Comment by johnmedina999** [comment]
Then we can close this issue.
