### ISSUE TITLE
joke command not working

### ISSUE THREAD

**Issue by johnmedina999** [abraker95/apex-sigma#56]
The `joke` command does not work. Calling the command gives the following exception.

![image](https://user-images.githubusercontent.com/12093732/88974074-ecd67500-d26c-11ea-92ca-76031f8d77dd.png)

The code for the command has the following two lines.

```
randomizer = random.randint(1, 6644)
joke_url = f'http://jokes.cc.com/feeds/random/{randomizer}'
```

Attempting to go to this URL with any number results in a redirect to the following URL: `https://www.youtube.com/standupfeeds/random/{randomizer}`, where `{randomizer}` is the number selected. I suggest finding another website with jokes to pull from.

**Comment by abraker95** [comment]
Idk how many people will miss this if it's nuked. Is it really worth going through the effort of fixing it?

**Comment by johnmedina999** [comment]
Perhaps we could replace it with trivia, as we have no trivia command. I know a website that I am particularly fond of: http://rumkin.com/fun/trivia/. We could pull some replace it with trivia from here.

Or perhaps our time is best spent elsewhere. What do you think?

**Comment by abraker95** [comment]
That would need to be its own issue in terms of adding a new command instead of replacing this one.

If you think you can implement it, you want to implement it, and you think it's worth implementing it, go for it.

**Comment by johnmedina999** [comment]
Then we can both agree that the `joke` command can be purged.
