### ISSUE TITLE
Feature request: custom color roles

### ISSUE THREAD

**Issue by johnmedina999** [abraker95/apex-sigma#57]
This has been requested for a long time, but the bot should be able to assign a custom color role per the request of a user. It would take a hex color code (e.g. `#FF8EE6`) and check if a role with that color already exists—if it does, then it would assign the user that role; if it doesn't it would make the role first.

Perhaps this should cost Kud (in order to give it a use), but this also might steer people away from the feature.

**Comment by abraker95** [comment]
I like the idea of it costing kud if it's a new color. How would people get kud tho?

**Comment by johnmedina999** [comment]
I believe people get Kud by just talking in chat—I do not know the rate, however. You could also gamble the Kud you have in order to get more with `slots` or `blackjack` or `fish`.

**Comment by abraker95** [comment]
imo this is what we should do for now:
- Make an add color command that is an admin command, adds to toggle roles
- Make a remove color command that is an admin command
- People can go to #requests to request for new color

I don't want people to be spamming the role list with colors, and making a functioning Kud system you propose is an entire project of its own

**Comment by johnmedina999** [comment]
I think that's OK. I liked putting the power to make roles in the people's hands, but if you think the role list is going to be disorganized as a result, that's alright too.

**Comment by johnmedina999** [comment]
There is already a command that creates roles, and its name is `createrole`. It'd be much more efficient to rework this to accept custom colors.

**Comment by johnmedina999** [comment]
How about this: I just rework `createrole` to accept colors, then the admin can manually set it as a toggleable role after. How does that sound?

There's little point in me making a whole new command which would consist of the same code as two other commands already in place.

**Comment by abraker95** [comment]
I like the idea of a separate role because then createrole has two purposes, and that just feels a bit messy

**Comment by johnmedina999** [comment]
> I like the idea of a seperate role

If by "role" you mean "command," then I'll get right to it.

**Comment by abraker95** [comment]
ah oops, yea
