### ISSUE TITLE
Clean color role switching

### ISSUE THREAD

**Issue by abraker95** [abraker95/apex-sigma#62]
Some people will eventually want to change to another color. If they do, the previous color they used will be still present, likely unused by anyone else. This will pollute the role list with unused roles. When changing to a other color role, the old color role should be nuked if nobody else is using it.

**Comment by johnmedina999** [comment]
This would be a modification to `togglerole`, correct?

**Comment by abraker95** [comment]
I am not sure. This is needs a discussion on how this should be handled.

I don't think `togglerole` will work because it applies, and should continue to apply, to all role in general sense. Another command such as `togglecolorrole` may add to the confusion. I think it's best to rename `addselfcolorrole` command to `setcolor` and change its functionality a bit.

It will function similarly to `addselfcolorrole`, but with a few key differences. Currently you need to do something like `>>addselfcolorrole #FF0000` then `>>togglerole #FF0000`. The `setcolor` command will allow to simply do `>>setcolor #FF0000` and it sets the user's color. If it changes from a different color, it should check if previous color role is used by anyone and remove it if not. Finally, allow a second parameter to give a specific user the color like `>>setcolor #FF0000 @abraker`

**Comment by johnmedina999** [comment]
If we're going to go with that plan, either one of two things will happen:

1. The new command requires elevated privileges. This means that the user will not be able to take the color off or change the color without the help of a moderator. I do not agree with this model, as this just puts a strain on mods that are busy doing other things.
2. The role does not require elevated privileges, allowing users to change their own color whenever they want. I believe that you disagree with this model because it would make a mess of color roles.

In either case, the changing of someone else's role would require elevated privileges no matter what.

**Comment by abraker95** [comment]
I am leaning towards 1. The way it works right now needs moderator intervention regardless. Later on when we have a working point system you proposed we can transition to 2.

**Comment by johnmedina999** [comment]
> The way it works right now needs moderator intervention regardless.

Yes, that's true. Are you prepared, however, to have double the amount of color change requests—one to put a color on and one to take it off?

**Comment by abraker95** [comment]
The `setcolor` command should take it off automatically. It swaps one color role for another

**Comment by johnmedina999** [comment]
Oh right. I'll get to it then.

**Comment by johnmedina999** [comment]
To clarify, there is no need to add the role to the list of self roles, correct?

**Comment by abraker95** [comment]
Hmm I think it's for the best that is the case. How would you figure out which one of the roles the user has is a color role?

**Comment by johnmedina999** [comment]
The name. If it fits the standard hex color code (alphanumeric 0–9, A-F; six characters), then it's a color role, and it gets deleted to make room for the new color role.

**Comment by johnmedina999** [comment]
Question: should this command also be able to remove a color role (without adding another one)? Or should removing be solely dedicated to `destroyrole`?

**Comment by abraker95** [comment]
solely dedicated to ...
